"""made nullable Message columns and set Comment user fk to Personne table-metadata

Revision ID: 5a9810a550c3
Revises: 5eb41e73f086
Create Date: 2022-10-15 10:27:42.038114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9810a550c3'
down_revision = '5eb41e73f086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_commentaire_client_id_personne'), 'personne', ['client_id'], ['id'])

    with op.batch_alter_table('entreprises', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_entreprises_mail'), ['mail'])
        batch_op.create_unique_constraint(batch_op.f('uq_entreprises_nomEntreprise'), ['nomEntreprise'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('lienPhoto',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('lienVideo',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('personne', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_personne_mail'), ['mail'])

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_publication_exposant_id_personne'), 'personne', ['exposant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_publication_exposant_id_personne'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exposant', ['exposant_id'], ['id'])

    with op.batch_alter_table('personne', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_personne_mail'), type_='unique')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('lienVideo',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('lienPhoto',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('entreprises', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_entreprises_nomEntreprise'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_entreprises_mail'), type_='unique')

    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_commentaire_client_id_personne'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###
