"""made nullable Message columns and set Comment user fk to Personne table

Revision ID: 5eb41e73f086
Revises: 0fcef44238e5
Create Date: 2022-10-15 10:14:40.524990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb41e73f086'
down_revision = '0fcef44238e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'personne', ['client_id'], ['id'])

    with op.batch_alter_table('entreprises', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nomEntreprise'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('lienPhoto',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('lienVideo',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'personne', ['exposant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'exposant', ['exposant_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('lienVideo',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('lienPhoto',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('entreprises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###
